Spring:
  application:
    name: ServiceRegistry
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761
  instance:
#    preferIpAddress: true
    hostname: localhost
#    nonSecurePort: 8080
